<a href="https://colab.research.google.com/github/jiraroj-wir/MUIC-ICCS261-Principles-of-Data-Science/blob/main/02_Statistics_with_NumPy_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Statistics with NumPy

Taken from https://www.packtpub.com/big-data-and-business-intelligence/data-visualisation-python

Modified by K. Bunchongchit kritya.bun@mahidol.ac.th on September 17, 2026.<br>Revised to include guided generative AI learning activities.

### Completed by Jiraroj Wiruchpongsanon on 21/09/2026

## AI Use Declaration 

This notebook contains guided AI activities, so complete this declaration. Replace ☐ with ☑ for each item that applies.

I acknowledge the use of gpt-6-astra on OpenAi codex to
<br>
☑ Understand before coding. Ask AI to explain the concept (e.g., axis) and restate it in your own words.
<br>
☑ Verify with the documentation. Check at least one AI claim against numpy.org, especially function defaults.
<br>
☐ Predict, then run. Calculate the result by hand on a small array before running code on the full dataset.
<br>
☑ Write first, then ask for review. Attempt the code yourself, then ask AI to critique it, not rewrite it.
<br>
☑ Understand errors, not just fixes. Ask why an error or unexpected result happened, and log the cause.
<br>
☐ Cross-check results. Confirm each answer with a second, independent method.
<br>
☐ Record and declare. Save your main prompts and complete the AI Use Declaration.<br>
☑ Others: Codex got access to this assignment codebase entirely. Before submission, i did have codex screen the entire notebook for mistakes, and have it recheck with the grading criteria. Only typo and wording correction were found, and codex did suggest me adding link/ source to those methods in Assignment 4 and 6 (according to the grading criteria). 

---

*If you choose not to use AI, write "No AI used" here and complete each AI Activity using the official NumPy documentation instead.*

In this exercise, we will load a dataset stored in `normal_distribution.csv` and calculate the mean of each row and each column. Our dataset has several rows, each containing floating point numbers around 100 with a standard deviation of 5.

Just to refresh your knowledge, the graph below shows that our dataset is Gaussian distributed:

[Normal Distribution](https://en.wikipedia.org/wiki/Normal_distribution)   
![](https://upload.wikimedia.org/wikipedia/commons/9/9e/Normal_Distribution_NIST.gif)

Here we are going to work on a dataset constructed from data stored in a CSV file with NumPy instead of using just Python. Below are possibly helpful resources for NumPy operations in this notebook:

- [Official documentation: The N-dimensional array (ndarray)](https://numpy.org/doc/stable/reference/arrays.ndarray.html)
- [Python Statistics Fundamentals: How to Describe Your Data](https://realpython.com/python-statistics/)

Complete the code in all sections with `numpy` except *Comparison with Python Lists*, which requires Python's built-in data types and functions.

If you see a variable name followed by the assignment symbol (`=`), assign the code for each task to the given variable in that cell. In other words, **do not** change the variable names. Feel free to add any line of code to a code cell, but make sure the result of each step is stored in the given variable.

If other modules, such as `statistics` and `pandas`, are used to complete this assignment (except in *Comparison with Python Lists*), the work will not be graded. In addition, keying the data directly into this notebook will result in a considerably lower score.

## How to Use Generative AI in This Notebook

The AI Activities in this notebook ask you to use AI as a **tutor and reviewer**, not as an answer generator. Follow these principles throughout:

1. **Understand before coding.** Ask AI to explain concepts, then restate them in your own words.
2. **Verify with the documentation.** AI tools can misstate function defaults or invent parameters. The official NumPy documentation is the final authority.
3. **Predict, then run.** Work out the expected result on a small example before running code on the full dataset.
4. **Write first, then ask for review.** Attempt each numbered step yourself before asking AI to critique your code.
5. **Understand errors, not just fixes.** When something goes wrong, ask *why*, not only *how to fix it*.
6. **Cross-check results.** Confirm an answer with a second, independent method.

**Example of a weak prompt:** *"Write code to find the mean of each column of my dataset."*

**Example of a strong prompt:** *"Explain what `axis=0` means in `np.mean()` using a 2×3 array. Then give me one question to test my understanding, without the answer."*

Record your prompts in the answer cells. You are evaluated on how critically you use AI output, not on how much you use it.

## AI Activity 1: Build a Mental Model (before writing any code)

Ask an AI tool to explain the following NumPy concepts: the `ndarray`, `dtype`, vectorized operations, and the `axis` argument. Ask it to give you a self-check question, and answer that question yourself before asking for feedback.

Then answer the questions in the cell below **in your own words**.

**Prompt(s) I used:**

To chatGPT (website): 

> Give me a good prompt for this, ill give it to codex. 
> 
> Ask an AI tool to explain the following NumPy concepts: the `ndarray`, `dtype`, vectorized operations, and the `axis` argument. Ask it to give you a self-check question, and answer that question yourself before asking for feedback.
> 
> Then answer the questions in the cell below **in your own words**.

***

chatGPT's answer to codex (gpt-6-astra, medium reasoning): 

> Explain the following NumPy concepts to me:
>
> * `ndarray`
> * `dtype`
> * vectorized operations
> * the `axis` argument
>
> Assume I already know basic Python, loops, lists, and simple NumPy syntax, but I am still learning how NumPy works conceptually.
>
> For each concept:
>
> 1. Give a concise definition.
> 2. Explain what it means in practice.
> 3. Give a small NumPy example.
> 4. Point out one common misunderstanding or mistake.
>
> For `axis`, explain it especially carefully using 1D and 2D arrays. Explain what `axis=0` and `axis=1` mean rather than just asking me to memorize "rows vs columns."
>
> After explaining everything, give me one self-check question that tests several of these concepts together.
>
> Do NOT answer the self-check question yet.
>
> Wait for me to answer it in my own words. Then:
>
> * tell me what parts of my answer are correct,
> * correct any mistakes precisely,
> * explain anything I seem to misunderstand,
> * and give me a concise improved version of my answer that I can use as a reference.
>
> Do not write my assignment response for me. The goal is for me to understand the concepts well enough to answer the assignment questions myself.

Follow up, codex (gpt-6-astra, medium reasoning): 

> y do scalar multiplication to x by 2, when x is i64. Then, z find the mean of axis 0, which is when other axis remain constant and we iterate over axis 0 (the row), to find the mean.
> 
> There's still 1-2 question that the first prompt didn't fully cover:
>
> - In my own words, what is the difference between a Python list and a NumPy ndarray?
>   
> - For a 2D array, what does axis=0 refer to? What does axis=1 refer to?
>   
> - One claim from the AI that I checked in the official documentation (include the link), and whether it was accurate:
> 
> Ignore the last one, I'll need further explanation on the first two questions. From my intuition, ndarray works like other programming language (except python) array, access each entry by pointer, not
  a list, so it'll be faster in general. And, axis=0 means that axis 0 can change, while other axis remain constant, for the iterator of numpy (like fsum or mean).


**In my own words, what is the difference between a Python list and a NumPy `ndarray`?**

A Python list stores references to Python objects in a dynamic array, so appending is usually cheap, and those objects can have different data types. A numeric NumPy ndarray stores values in a buffer, using a single data type (dtype). It uses shape and strides to locate each entry inside the buffer. This representation supports efficient vectorized calculations. Using Python loops often reduces that performance advantage, so we should avoid it.

**For a 2D array, what does `axis=0` refer to? What does `axis=1` refer to?**

View the ndarray as if it was in a cartesian coordinate system, 

$$A(i, j, k, ..., n)$$, 

then `axis=0` written in `i` would be the outer most shell, while `axis=n` would be the inner most shell. For example

```python
 A = np.array([
      [[1, 2, 3],
       [4, 5, 6]],

      [[10, 20, 30],
       [40, 50, 60]]])
```

could be written as $A(2, 2, 3)$, then **reduction** along an axis would means having every other axis remain constant while doing the operation on that axis, thus the array is reduced, 1 dimension less, into an array of those other axis that remain constant. 

So, `axis=0` would means, the row and column remain stationary, and we do operation on the external layer, as $(1, 10), (2, 20), (3, 30), (4, 40), (5, 50), (6, 60)$, and we're left with $A'(2, 3)$

For `axis=1`, the external layesr and the columns remain, and we do operation on the rows, as $(1, 4), (2, 5), (3, 6), (10, 40), (20, 50), (30, 60)$, and we're left with $A'(2, 3)$

For `axis=2`, the external layers and the rows remain, and we do operation on the columns, as $(1, 2, 3), (4, 5, 6), (10, 20, 30), (40, 50, 60)$, and we're left with $A'(2, 2)$

**One claim from the AI that I checked in the official documentation (include the link), and whether it was accurate:**

Claim: summing along a single axis removes that dimension from the output shape by default.

source: https://numpy.org/doc/stable/reference/generated/numpy.sum.html

Indeed, the numpy documentation did mention that, and it behave as expected on my test.

## Loading our dataset

1. Import the necessary dependencies.

In [1]:
import numpy as np

2. If you are doing this assignment via Google Colab, run this code to generate the URL for the data file on the cloud drive. You must allow this notebook to access your Google credentials.

   If you use a desktop IDE, just skip this step.

In [2]:
CSV_URL = 'https://drive.google.com/uc?export=download&id=1WHRhl8L3qeXoHSvp7I9viokJjBa7-zWa'

3. Load the dataset.

   If you are using Google Colab, run the code below.

In [3]:
dataset = np.genfromtxt(CSV_URL, delimiter=',')

```text
Ps. I'm using jupyter lab + lvim (molten), locally, and the download script did work. So, I didn't download the csv file manually as instructed. 
```

   If you are running a local IDE,

   3.1 Download the data file and place it in the same folder as this notebook.

   3.2 Make a code cell underneath this cell and run the code below. Adjust your data file path if necessary.

   `dataset = np.genfromtxt('normal_distribution.csv', delimiter=',')`

4. Look at the dataset by running the code cell below.

In [4]:
dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749

## After loading our dataset

To get a quick overview of our dataset we want to print out its "shape". This gives an output of the form `(rows, columns)`.

5. Print the shape of our dataset.

In [5]:
shape = dataset.shape
shape

(24, 8)

6. Extract the first row.

In [6]:
first_row = dataset[0, :]
first_row

array([ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
        98.74986914,  98.80833412,  96.81964892,  98.56783189])

7. Calculate the mean for the first row.

In [7]:
mean_row0 = first_row.mean()
mean_row0

np.float64(100.177647525)

8. Extract the first column.

In [8]:
col0 = dataset[:, 0]
col0

array([ 99.14931546,  92.02628776,  95.66253664,  91.37294597,
       101.20862522, 102.80387079, 106.71751618,  96.02548256,
       105.30350449, 110.44484313, 101.3514185 ,  97.21315663,
        95.65982034, 100.39303522, 103.1521596 , 106.11454989,
        96.78266211, 101.86186193,  97.49594839,  96.76814836,
       106.89005002,  99.80873105,  96.10020311,  94.11176915])

9. Calculate the mean for the first column.

In [9]:
mean_col0 = col0.mean()
mean_col0

np.float64(99.76743510416668)

## AI Activity 2: Predict First with a Toy Array

Before finding the mean of every row and column in the full dataset, test your understanding on an array small enough to calculate by hand.

**Step A.** Without running any code, calculate by hand what each expression below returns, and write your predictions in the next cell.

```python
toy = np.array([[2, 4, 6],
                [8, 10, 12]])

np.mean(toy)           # (i)
np.mean(toy, axis=0)   # (ii)
np.mean(toy, axis=1)   # (iii)
```

**Step B.** Run the code in the cell after that to check your predictions.

If a prediction was wrong, you may ask AI to explain the difference, but write the explanation in your own words.

**My predictions (by hand, before running code):**

(i) [7]

(ii) [5, 7, 9]

(iii) [4, 10]

**Were my predictions correct? If not, what did I misunderstand?**

It is arithmetically correct. I knew it should be float, but didn't write it out explicitely. The only mismatch is the display format. And, $[7]$ might imply scalar in mathematic, but in this case, it should only be $7$. 

In [10]:
toy = np.array([[2, 4, 6],
                [8, 10, 12]])

print(np.mean(toy))
print(np.mean(toy, axis=0))
print(np.mean(toy, axis=1))

7.0
[5. 7. 9.]
[ 4. 10.]


Now that you have practiced with the toy examples, transfer your knowledge to the following steps.

---

10. Find the mean for each row.

In [11]:
mean_by_row = dataset.mean(axis=1)
mean_by_row

array([100.17764752,  97.27899259, 100.20466135, 100.56785907,
       100.98341406,  97.83018578, 101.49052285,  99.75332252,
       101.89845125,  99.77973914, 101.013081  , 100.54961696,
        98.48256886,  98.49816126, 101.85956927,  97.05201872,
       102.62147483, 101.21177037,  99.58777968,  98.96533534,
       103.85792812, 101.89050288,  99.07192574,  99.34233101])

11. Find the mean for each column.

In [12]:
mean_by_col = dataset.mean(axis=0)
mean_by_col

array([ 99.7674351 ,  99.61229127, 101.14584656, 101.8449316 ,
        99.04871791,  99.67838931,  99.7848489 , 100.44049274])

12. Calculate the mean for the whole matrix.

In [13]:
mean = (mean_by_col.mean() == mean_by_row.mean() == dataset.mean()) * (dataset.mean())
mean

np.float64(100.16536917390624)

```text
Ps. codex did suggest me using `np.allclose()` instead of `==`. I supposed i just got lucky this time that it worked. 
```

When looking at the mean values we can really nicely see the effect of calculating the mean of several values taken from a normal distribution. If we had even more data we would get even closer to 100.

---


## AI Activity 3: Verify Against the Official Documentation

The introduction states that the data has a standard deviation of 5. NumPy can calculate either the **population** standard deviation or the **sample** standard deviation, depending on a parameter.

**Step A.** Ask an AI tool what the default behaviour of `np.std()` is and which parameter changes it. Record its answer below.

**Step B.** Check that answer against the official NumPy documentation for `np.std()`.

**Step C.** Complete steps 12a and 12b.

---

Now that you have learned the concepts, transfer them to the following steps.


**What the AI said about the default of `np.std()`:**

To codex (gpt-6-astra, high reasoning): 

\> what is the default behaviour of `np.std()`?

> np.std(a) computes the population standard deviation of all elements in a.
>
> Defaults:
>
> - axis=None: uses all elements, returning a single value.
> - ddof=0: divides the squared deviations by N, not N − 1.
> - NaN values propagate, so an array containing NaN returns NaN. Use np.nanstd() to ignore them.
>   
> a = np.array([1, 2, 3])
> 
> np.std(a)         # ≈ 0.8165 (population standard deviation)
> 
> np.std(a, ddof=1) # 1.0      (sample standard deviation)
> 
> For a 2D array, use axis=0 for standard deviation per column or axis=1 per row.

**What the official documentation says (include the link):**

source: https://numpy.org/doc/2.5/reference/generated/numpy.std.html#numpy.std

```text
Ps. Only the description of the function, there's also parameters, returns and additional notes in the official NumPy documentation as well.
```

> Compute the standard deviation along the specified axis.
>
> Returns the standard deviation, a measure of the spread of a distribution, of the array elements. The standard deviation is computed for the flattened array by default, otherwise over the specified axis.
>

Also, there's additional notes on the bottom part

> There are several common variants of the array standard deviation calculation. Assuming
> the input `a` is a one-dimensional NumPy array and `mean` is either provided as an argument
> or computed as `a.mean()`, NumPy computes the standard deviation of an array as:
>
> ```python
> N = len(a)
> d2 = abs(a - mean)**2  # abs is for complex `a`
> var = d2.sum() / (N - ddof)  # note use of `ddof`
> std = var**0.5
> ```
>
> Different values of the argument `ddof` are useful in different contexts. NumPy’s default
> `ddof=0` corresponds with the expression:
>
> $$\sqrt{\frac{\sum_i |a_i-\bar{a}|^2}{N}}$$
>
> which is sometimes called the “population standard deviation” in the field of statistics
> because it applies the definition of standard deviation to `a` as if `a` were a complete
> population of possible observations.
>
> Many other libraries define the standard deviation of an array differently, e.g.:
>
> $$\sqrt{\frac{\sum_i |a_i-\bar{a}|^2}{N-1}}$$
>
> In statistics, the resulting quantity is sometimes called the “sample standard deviation”
> because if `a` is a random sample from a larger population, this calculation provides the
> square root of an unbiased estimate of the variance of the population. The use of $N-1$ in
> the denominator is often called “Bessel’s correction” because it corrects for bias (toward
> lower values) in the variance estimate introduced when the sample mean of `a` is used in
> place of the true mean of the population. The resulting estimate of the standard deviation is
> still biased, but less than it would have been without the correction. For this quantity, use
> `ddof=1`.
>
> Note that, for complex numbers, `std` takes the absolute value before squaring, so that the
> result is always real and nonnegative.
>
> For floating-point input, the standard deviation is computed using the same precision the
> input has. Depending on the input data, this can cause the results to be inaccurate,
> especially for float32 (see example below). Specifying a higher-accuracy accumulator using
> the `dtype` keyword can alleviate this issue.

**Did they agree? If not, which was wrong?**

They do agree. Codex version is concise and a bit easier to understand (maybe personalize as well), but the official NumPy documentation is ... an official documentation, so in case of any inconsistency, we should stick to it. The documentation also include the entire list of parameters (more than what jupyter lab pop-up documentation shows), returns, link to the actual source code and more clarification in the official notes regarding the `ddof` parameter.

---



Now that you have practiced with the toy examples, transfer your knowledge to the following steps.

12a. Calculate the **population** standard deviation of the whole matrix.

In [14]:
std_pop = np.std(dataset)
std_pop

np.float64(4.838197554269257)

12b. Calculate the **sample** standard deviation of the whole matrix.

In [15]:
std_sample = np.std(dataset, ddof=1)
std_sample

np.float64(4.850846458349645)

**Reflection Questions:**

1. Are your results close to 5?

Both population SD and sample SD are close to 5, they're around $4.84$ and $4.85$ respectively. Whether they're close enough depends on the tolerance we set, which the question didn't specify. So using relative difference

$$\frac{|\text{SD}-5|}{5}\times100%$$

the results are 3.24% and 2.98% below 5.0, which would be acceptable if our tolerance were set to 5%. Even though the dataset was generated via a well-established RNG package, a finite random sample isn't expected to have an SD of exactly 5, so this difference alone doesn't mean the result is unacceptable.

  2. The two results are very close. Explain why the difference between population and sample standard deviation is small for this dataset. (Hint: consider how many values are in the dataset.)

As population SD is expressed by

$$\sqrt{\frac{\sum_i |a_i-\bar{a}|^2}{N}}$$

and

$$\sqrt{\frac{\sum_i |a_i-\bar{a}|^2}{N-1}}$$

for sample SD, where $N$ is the dataset size.

In our case, there were 192 values in the dataset, and as the numerator remains the same for both the population SD and sample SD, the only difference is in the denominator, which differs by 1. This is relatively small compared to our $N = 192$.

  3. Would the difference be larger or smaller for a dataset of only 5 values? Why?

The relative difference would be larger for a smaller dataset (such as 5 values), as population SD is expressed by

$$\sqrt{\frac{\sum_i |a_i-\bar{a}|^2}{N}}$$

and

$$\sqrt{\frac{\sum_i |a_i-\bar{a}|^2}{N-1}}$$

for sample SD, where $N$ is the dataset size. So, a change of the denominator from $5 \to 4$ would be proportionally larger than the one from $192 \to 191$, even though both differ by 1.

## AI Activity 4: Missing Values and Unexpected Results

Real datasets often contain missing values. The code below loads a small CSV-style dataset in which two values are blank. Run it and look at how `np.genfromtxt` represents the blanks.

In [16]:
messy = np.genfromtxt(['100.5,98.2,101.1',
                       '99.0,,102.3',
                       '97.8,100.4,'], delimiter=',')
messy

array([[100.5,  98.2, 101.1],
       [ 99. ,   nan, 102.3],
       [ 97.8, 100.4,   nan]])

12c. Calculate the mean of the whole `messy` array using the same approach as step 12.

In [17]:
messy_mean = messy.mean()
messy_mean

np.float64(nan)

The result of 12c is probably not useful. Use AI to find out **why** this happens, and to find a NumPy function that calculates the mean while ignoring missing values. Verify the function in the official documentation before using it.

12d. Calculate the mean of `messy`, ignoring missing values.

source: https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html

In [18]:
messy_nanmean = np.nanmean(messy)
messy_nanmean

np.float64(99.89999999999999)

**Prompt(s) I used:**

To codex (gpt-6-astra, medium reasoning): 

\> The result of 12c is np.float64(nan). There probably is a configuration or another method that works with NaN?

Follow-up, codex ((gpt-6-astra, medium reasoning): 

\> Explain why messy.mean() returns NaN and how np.nanmean() handles missing entries in the sum and count. Include the official NumPy documentation so I can verify the explanation.

**In my own words, why did 12c give that result?**

The mean() method includes every entry of the ndarray. Since the blank entries were loaded as NaN, representing missing values here, the summation used to calculate the mean results in NaN. Dividing by the number of entries still gives NaN:

$$\frac{\text{NaN}}{N} = \text{NaN}$$

**Error and issue log.** Record any error message or unexpected result you met anywhere in this notebook, its cause, and how you fixed it. Write "None" if you had no errors.

```text
Ps. I think this part/ table should be at the top of the notebook. I didn't keep track of the errors that occours throughout the time I was completing this assignment. So, i'll just ask codex to writeout this part for me, though quite often that i use other approach in fixing or avoid those issues: google search, lsp warnings, pop-up documentation in jupyter lab, ect. 
```

| Step | Error or unexpected result | Cause (in my own words) | Fix |
|---|---|---|---|
| 12 | My expression returned the correct mean, but could return zero if the comparison failed. | I multiplied the mean by an exact-equality check. Floating-point rounding could make the check return `False`, which acts as zero. | Identified the risk. The recommended fix is to calculate `dataset.mean()` directly and use `np.allclose()` separately for verification; I haven't applied this change yet. |
| 12c–12d | `messy.mean()` returned `NaN`, as anticipated by the activity. | The blank entries were loaded as `NaN`, which propagated through the mean calculation. | Used `np.nanmean(messy)` in 12d to ignore missing entries, giving approximately 99.9. |
| `.md` written parts | typos, sometimes misconcepts | human error, I'm dumb | codex inform me about the typo or misconcepts, and (for misconcepts or technical mistakes) explain and suggest fixes. |
| this step | codex cli can't reply a copyable `.md` table | codex cli program will always tries to turn plane `.md` script for table into some nice TUI | I had codex write into a random file in the same directory, then copy from that with my text editor of choice |

## AI Activity 5: Code Review

Choose **one** of steps 6 to 12 where you are least confident about your code. Paste only your own code for that step into an AI tool and ask it to **critique** the code rather than rewrite it. For example:

*"Here is my code for step 11, which finds the mean of each column of a 2D NumPy array. Is it correct? Is there a more idiomatic NumPy approach? Explain your reasoning, but don't rewrite the whole thing."*

Complete the cell below.

**Step reviewed:** step 6

**My original code:**

```python
first_row = dataset[0, :]
first_row
```

**Summary of the AI's feedback (in my own words):**

The code is correct, but `first_row` shares data with `dataset`, so changing `first_row`'s elements would also change the original (`dataset`) dataset. No change is needed here because the code only use the extracted row to calculate mean.

**What I changed, or chose not to change, and why:**

I chose not to change, because the initial code works, and i'm lazy

## Comparison with Python Lists

In the steps below, try to use just Python's built-in data types and functions, and the `statistics` module, to complete each task with the same dataset that we used in the previous section. No `NumPy`, no `pandas`. If it is not possible for you, just write `# Impossible` in the cell.

13. Convert the NumPy array to a Python list.

In [19]:
data_lst = dataset.tolist()
data_lst

[[99.14931546,
  104.03852715,
  107.43534677,
  97.85230675,
  98.74986914,
  98.80833412,
  96.81964892,
  98.56783189],
 [92.02628776,
  97.10439252,
  99.32066924,
  97.24584816,
  92.9267508,
  92.65657752,
  105.7197853,
  101.23162942],
 [95.66253664,
  95.17750125,
  90.93318132,
  110.18889465,
  98.80084371,
  105.95297652,
  98.37481387,
  106.54654286],
 [91.37294597,
  100.96781394,
  100.40118279,
  113.42090475,
  105.48508838,
  91.6604946,
  106.1472841,
  95.08715803],
 [101.20862522,
  103.5730309,
  100.28690912,
  105.85269352,
  93.37126331,
  108.57980357,
  100.79478953,
  94.20019732],
 [102.80387079,
  98.29687616,
  93.24376389,
  97.24130034,
  89.03452725,
  96.2832753,
  104.60344836,
  101.13442416],
 [106.71751618,
  102.97585605,
  98.45723272,
  100.72418901,
  106.39798503,
  95.46493436,
  94.35373179,
  106.83273763],
 [96.02548256,
  102.82360856,
  106.47551845,
  101.34745901,
  102.45651798,
  98.74767493,
  97.57544275,
  92.5748759],
 [105.303

14. Extract the first column of `data_lst`.

In [20]:
p_col0 = [row[0] for row in data_lst]
p_col0

[99.14931546,
 92.02628776,
 95.66253664,
 91.37294597,
 101.20862522,
 102.80387079,
 106.71751618,
 96.02548256,
 105.30350449,
 110.44484313,
 101.3514185,
 97.21315663,
 95.65982034,
 100.39303522,
 103.1521596,
 106.11454989,
 96.78266211,
 101.86186193,
 97.49594839,
 96.76814836,
 106.89005002,
 99.80873105,
 96.10020311,
 94.11176915]

15. Find the mean for each row of `data_lst`.

In [21]:
p_mean_by_row = []
for row in data_lst: 
    p_mean_by_row.append(sum(row)/ len(row))
    
p_mean_by_row = p_mean_by_row
p_mean_by_row

[100.177647525,
 97.27899259,
 100.2046613525,
 100.56785907,
 100.98341406125,
 97.83018578125,
 101.49052284625,
 99.7533225175,
 101.89845124874999,
 99.77973914,
 101.01308100125,
 100.54961695875001,
 98.48256886,
 98.49816125875,
 101.85956927125,
 97.0520187175,
 102.6214748325,
 101.211770365,
 99.58777967875,
 98.965335345,
 103.8579281225,
 101.89050288125,
 99.0719257425,
 99.34233100624999]

16. Find the mean for each column of `data_lst`.

In [22]:
p_mean_by_col = []
for j in range(len(data_lst[0])):
    column = [row[j] for row in data_lst]
    p_mean_by_col.append(sum(column)/ len(column))

p_mean_by_col = p_mean_by_col
p_mean_by_col

[99.76743510416667,
 99.61229127083334,
 101.14584655750001,
 101.84493159750001,
 99.04871790958333,
 99.67838931458334,
 99.78484889958334,
 100.4404927375]

17. Calculate the mean for the whole `data_lst`.

In [23]:
# using this chance to tryout `np.allclose` that codex recommended earlier
# p_mean = np.allclose(sum(p_mean_by_row)/ len(p_mean_by_row), sum(p_mean_by_col)/ len(p_mean_by_col)) * (sum(p_mean_by_row)/ len(p_mean_by_row))
# no NumPy!
p_mean = sum(p_mean_by_row) / len(p_mean_by_row)
p_mean

100.16536917390624

## AI Activity 6: Cross-Check Your Results

You have now calculated the same statistics in two independent ways. If both approaches are correct, their results should match. **In this section only, both NumPy and Python lists may be used.**

Comparing floating point numbers with `==` can be unreliable. Ask an AI tool why, then test the claim yourself by running `0.1 + 0.2 == 0.3` in a new code cell. Find a NumPy function that checks whether two arrays are *approximately* equal, and verify it in the official documentation.

source: https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

In [24]:
0.1 + 0.2 == 0.3

False

18a. Check whether `mean_by_row` and `p_mean_by_row` are approximately equal.

In [25]:
rows_match = np.allclose(mean_by_row, p_mean_by_row)
rows_match

True

18b. Check whether `mean_by_col` and `p_mean_by_col` are approximately equal.

In [26]:
cols_match = np.allclose(mean_by_col, p_mean_by_col)
cols_match

True

18c. Check whether `mean` and `p_mean` are approximately equal.

In [27]:
overall_match = np.allclose(mean, p_mean)
overall_match

True

**Why is `==` unreliable for comparing floating point results? (In your own words.)**

As floating point system (IEEE double precision for python float, i supposed) got limited precision, and is represented with finite sum of powers of 2 (inculding negative exponents). It cannot represent most float precisely, thus there usually be small rounding errors for most value this floating point system trying to represent. 

Meanwhile, `==` would compare the exact numerical value, without any tolerance, and so $0.1 + 0.2 \ne 0.3$ in Python's float. 

**Did all three checks return `True`? If any returned `False`, what was the cause?**

All three checks return `True`.

## Final Reflection

1. Describe **one** AI output in this notebook that was incorrect, incomplete, or not what you needed. How did you notice, and what did you do?

gpt-6-astra didn't make any mistake throughout this assignment. Though, there were time when I didn't like the answer or response text: response didn't clear all my confusion or when the generated code were too advance (specific python syntax that won't work on any other programming languages, i prefer not using those); which i just change the prompt or issue a follow-up message. 

2. Which NumPy concept from this notebook could you now explain to a classmate **without** using AI?

Maybe the axis parameter for those method like `sum` or `mean` that do reduce the dimension of ndarray.

3. Comparing steps 10–12 with steps 15–17, what advantages does NumPy offer over Python lists for this kind of task?

Speed and convenience, less prone to human error. 