<a href="https://colab.research.google.com/github/jiraroj-wir/MUIC-ICCS261-Principles-of-Data-Science/blob/main/Copy_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy - An Effective Way for Computation
*B. mathayomchan & K. Bunchongchit<br>
Last updated on January 8, 2026*

## TOPICS:

1. What is NumPy?
    * 1.1 NumPy Arrays
        * 1-d array
        * 2-d array  
2. CRUD
    * 2.1 CREATE
    * 2.2 READ
    * 2.3 UPDATE
    * 2.4 DELETE
3. Some useful functions
4. Operations with matrices

## 1. What is NumPy?
>NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. - NumPy.org

The key characteristics of NumPy:
* NumPy arrays have a fixed size (unlike list Python that you can append)
* All elements must be the same type ( cannot mix type like list in Python)

**It sounds very limited, what should we use it?**

Answer: **It is fast!** In data science we have to deal with a lot of data points. If the underlying data structures are slow, it will significantly affect the performance.

**How will we use NumPy in this course?**

We will use NumPy arrays:

* Vector : 1-d array
* Matrix : 2-d array

## 1.1 NumPy Arrays
To create NumPy Arrays, we need to import it first

_Note: It is a convention to give a shorter name to the library. Here, we use **np** as the nickname of it._

In [ ]:
import numpy as np

### 1-d array
Now, we can create a NumPy array. We can by using data from a list.

In [ ]:
my_list = [11, 13, 15] # plain Python command
np.array(my_list) # We create a numpy array from the Python list

array([11, 13, 15])

We just create a 1-d array (vector). Let's assign that to a variable. We can get the dimension of our array by calling **.shape** and then we will get a tuple where the elements are the dimentions.

In [ ]:
my_list = [11, 13, 15]
x = np.array(my_list)
x.shape   # Dimension of the array

(3,)

**We can access the element by using an index.**  Note: Index start at 0.

In [ ]:
x[1]

np.int64(13)

Using third-party modules bring new data structures into Python. It is a good idea to see what data structure we are using. We can call **type(varible)** to see the data type.

In [ ]:
type(x)

numpy.ndarray

In [ ]:
type(my_list)

list

Note that the type of the N-dimensional array is **ndarray**.
The ndarray has a property **shape** that holds a tuple. The length of the tuple indicates **N**, the dimension of the array, and the number in each location indicates the number of elements in the corresponding dimension.

Since we just make a 1-d array, the length of the `shape` tuple is 1.

In [ ]:
print(type(x.shape))  # This will be a tuple.
print(len(x.shape))  # This will show length of the tuple.

<class 'tuple'>
1


A quick reminder about tuple.


In [ ]:
a = (3, 4)
print(type(a)) # this shall be a tuple
print(len(a)) # this shall be 2

<class 'tuple'>
2


### 2-D Arrays
In the same manner with creating a 1-d array in NumPy, we can create a 2-d array by using data from a list.

First, we create a list of lists.

```my_2d_list = [ ? , ? , ? ]```

Each `?` is also a list.


In [ ]:
my_2d_list = [ [1, 2] , [3, 4] , [5, 6] ]
my_2d_list

[[1, 2], [3, 4], [5, 6]]

Now, we can create an array.

In [ ]:
y = np.array(my_2d_list)
y

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(y)
print(my_2d_list)

[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


We can access using index.

In [ ]:
# Accessing the value of y at row 2 column 1 (aka the intersection of the third row and the second column)
y[2, 1]

np.int64(6)

In [ ]:
my_2d_list[2][1]

6

In [ ]:
y[2]  # Accessing the third element of y (aka the third row)

array([5, 6])

In [ ]:
my_2d_list[2, 1]

TypeError: list indices must be integers or slices, not tuple

In [ ]:
y[2][1]

np.int64(6)

# Break time (& Practice Time)!

Until 3:15 PM

### Practice Time ###

**Challenge #1**
Creat a 2-d array with data as shown on the image below. Assign the created array to a variable <code>z</code>.
<img src="https://drive.google.com/uc?id=1eQlKUphQQRLZWo5H4JNNFAwquvUgG4zr" width=60% />

Write your code here.

In [ ]:
z_list = [ [10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120] ]

In [ ]:
z = np.array(z_list)
print(z)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


**Challenge #2**

Creat a 3-d array with data as shown on the image below. Assign the created array to a variable <code>m</code>.

<img src="https://drive.google.com/uc?id=1KN8cL8VhjWE6ngtC3TvyoJ7l1SVVz539" width=80%/>

If you code the matrix in a wrong way, it would be a different matrix. So check the shape of your array as well as elements in the array.


Why so? Axes are different than dimensions. Consider the following images.

<img src="https://drive.google.com/uc?id=1lIbRhsrZI75OcudMaRFHnzn0dg6QwfFJ" width=25% stlye="float:right;"/>

Image ref: [Indexing and slicing numpy arrays](https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/)

In [ ]:
# Write your code here.
m_list = [ [ [1, 2, 3], [4, 5, 6] ], [ [10, 20, 30], [40, 50, 60] ], [ [100, 200, 300], [400, 500, 600] ] ]
m = np.array(m_list)
print(m)

[[[  1   2   3]
  [  4   5   6]]

 [[ 10  20  30]
  [ 40  50  60]]

 [[100 200 300]
  [400 500 600]]]


Then, try your matrix with the test cases below.

In [ ]:
assert m[0, 0, 0] == 1
assert m[1, 1, 0] == 40
assert m[0, 0, 1] == 2
assert m[2, 1, 2] == 600

## 3. CRUD

CRUD represents four basic operations on persistent storage, namely **create**, **read**, **update**, and **delete**.

### 3.1 CREATE
We can create a NumPy array from a list.

In [ ]:
my_2d_list = [ [1 ,2] , [3, 4] , [5, 6] ]
my_np_arr = np.array(my_2d_list)
my_np_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

### 3.2 READ
We can access the element by using indexes. With the same manner as Python, the index starts from 0.

Accessing a specific element

In [ ]:
my_np_arr[2, 1]  # [ROW, COL]

np.int64(6)

In [ ]:
my_2d_list[2, 1]  # Should be the same as above, but it's not!

TypeError: list indices must be integers or slices, not tuple

In [ ]:
my_2d_list[2][1]

6

Accessing a row

In [ ]:
my_np_arr[1]

array([3, 4])

In [ ]:
my_np_arr[1, :]

array([3, 4])

Accessing a column

In [ ]:
my_np_arr[:, 0]

array([1, 3, 5])

In [ ]:
my_np_arr[:, 0].shape

(3,)

In [ ]:
my_np_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
my_np_arr[:, [0]]

array([[1],
       [3],
       [5]])

In [ ]:
my_np_arr[:, [0]].shape

(3, 1)

Slice the first two rows of the first column.

In [ ]:
my_np_arr[:2, 0]

array([1, 3])

In [ ]:
my_np_arr[-2:, 0]

array([3, 5])

In [ ]:
my_np_arr[-2:-1, 0]

array([3])

In [ ]:
my_2d_list[:, 0]

TypeError: list indices must be integers or slices, not tuple

### 3.3 UPDATE
1. Change value
2. Append data (returning a new array)

We can change value by reassigning the new value to the array.

In [ ]:
my_np_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
my_np_arr[2, 1] = 555
my_np_arr

array([[  1,   2],
       [  3,   4],
       [  5, 555]])

We can append two arrays together. It will flatten to 1d, join them, and return a **new** array.

In [ ]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[7, 8]])
arr3 = np.append(arr1, arr2) # It returns a new array. It doesn't add arr2 to arr1.
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr2

array([[7, 8]])

Notice that the dimension is not 4 rows 2 columns. We have to reshape this 1-d array to the desired dimension.

In [ ]:
print(arr3.shape) # Will get (8,)
arr4 = arr3.reshape(4, 2) # It doesn't change arr3, but use data to make a new array
print(arr3)
print('---')
print(arr4)

(8,)
[1 2 3 4 5 6 7 8]
---
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Notice that `arr1` and `arr2` still stay the same.

In [ ]:
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

### 3.4 DELETE
We cannnot delete existing element. NumPy makes a new array without the deleted item.

```python
np.delete(array, index, axis)
```
Axis 0 is along rows, and Axis 1 is along the columns.

In [ ]:
arr1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

We want to delete the row that has [5, 6]. It is Row 2 Axis 0.

In [ ]:
arr2 = np.delete(arr1, 2, 0)
arr2

array([[1, 2],
       [3, 4],
       [7, 8]])

Now, let's try to delete column that has `2 4 6 8`. That's index 1, axis 1.

In [ ]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
arr3 = np.delete(arr1, 1, 1)
arr3

array([[1],
       [3],
       [5],
       [7]])

Keep in mind that NumPy arrays don't change. When we modify it, the modified one is the **NEW ARRAY**.

In [ ]:
print(arr1)
print('---')
print(arr3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
---
[[1]
 [3]
 [5]
 [7]]


## 4. Some useful functions

Create array with elements from START(default is 0) to STOP (exclusive). You can also specify step size.

In [ ]:
arr11 = np.arange(0, 10)
arr11

In [ ]:
arr12 = np.arange(0, 10, 4)
arr12

In [ ]:
arr13 = np.zeros(3)
arr13

In [ ]:
arr14 = np.zeros((2, 3))
arr14

In [ ]:
arr15 = np.ones((4, 5))
arr15

In [ ]:
arr16 = np.identity(3)
arr16

In [ ]:
arr17 = np.eye(5)
arr17

In [ ]:
arr18 = np.eye(5, k=1)
arr18

In [ ]:
arr19 = np.random.rand(3, 2)
arr19

In [ ]:
p = np.random.randint(0, 100, 30)
p

In [ ]:
p.reshape(5, 6)

In [ ]:
p

In [ ]:
p.min()

In [ ]:
p.argmin()  # Returns the indices of the minimum values along an axis

In [ ]:
p.max()

In [ ]:
p.argmax()  # Guess what?

## 5. Operations with matrices

### ADD
If you remember, when we have two lists and we add them together.
What would be the result?


In [ ]:
a = [1, 3, 5]
b = [20, 30, 40]
c = a + b
c

With NumPy, let's try to **ADD** them again.

In [ ]:
d = np.array([1, 2, 3])
e = np.array([10, 100, 1000])
d + e

**If the dimensions are not the same, you will get an error message.**


In [ ]:
d = np.array([1, 2, 3, 4])
e = np.array([10, 100, 1000])
d + e

**What if we want to append an array to another array?**
You cannot add data to an existing array. However, you can copy elements and append a new one to form a new array. This can be slow if you have a lot of data points.

In [ ]:
f = np.array(["ha", "ho"])
g = np.array(["hey", "how"])
h = np.append(f, g)
h

### MULTIPLY
We can multiply a matrix with a scalar.

Try:
```python
g = np.array([1, 2, 3])
2*g
```

In [ ]:
g = np.array([1, 2, 3])
2*g

In [ ]:
[2, 4, 6] * 2

In [ ]:
i = np.array([2, 3, 4])
i*i

In [ ]:
[2, 4, 6] * [2, 4, 6]